user:
  outputs:
    default:
      account: FRNDEDI-UL76795
      auth_type: password
      client_session_keep_alive: false
      connect_retries: 3
      connect_timeout: 30
      database: RDL_TMS_SVT
      password: Darksoul@2026M
      retry_on_database_errors: true
      role: null
      schema: CA
      threads: 6
      type: snowflake
      user: cijom07
      warehouse: COMPUTE_WH
  target: default
